arms:
  leader:
    serial: 5B41532862
    id: my_awesome_leader_arm
  follower:
    serial: 5B41532784
    id: my_awesome_follower_arm
cameras:
  wrist: '0x111100029930858'
  left_rear: '0x11120000bda1376'
  right_rear: '0x11130000bda1376'
record:
  fps: 30
  width: 640
  height: 480
